name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: get rust
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: default
        components: rustfmt
    - name: cargo build
      run: cargo build --release
    - name: cargo test
      run: cargo test
