name: checks
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions-rs/cargo@v1
      with:
        command: fmt
    - name: check changed
      run: |
        if [[ -n $(git status -s) ]] 
        then
          echo 'cargo fmt modified files. checks failed. check the .github/workflows/checks.yml file. Run `cargo fmt` and commit your changes.'
          exit 1
        fi
